version: '3.8'

services:
  postgres:
    environment:
      POSTGRES_DB: app_test
    command: postgres -c log_statement=all

  mongodb:
    environment:
      MONGO_INITDB_DATABASE: app_test

  api:
    build:
      context: .
      dockerfile: docker/development/Dockerfile
    working_dir: /app
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    ports:
      - "3030:3030"
    environment:
      NODE_ENV: development
      DATABASE_URL: postgres://dev:dev@postgres:5432/app_test
      MONGODB_URL: mongodb://mongodb:27017/app_test
      REDIS_URL: redis://redis:6379
    depends_on:
      postgres:
        condition: service_healthy
      mongodb:
        condition: service_healthy
      redis:
        condition: service_healthy
    command: pnpm --filter api dev

  web:
    build:
      context: .
      dockerfile: docker/development/Dockerfile
    working_dir: /app
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
      REACT_APP_API_URL: http://localhost:3030
    depends_on:
      - api
    command: pnpm --filter web dev

volumes:
  node_modules:
